/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Room, Experience, SpecialPackage } from "./types";

import imgRoomsview from "./public/images/coolcottage_roomsview.jpg";
import imgBedrooms from "./public/images/coolcottage_bedrooms.jpg";
import imgBedroom from "./public/images/coolcottage_bedroom.jpg";
import imgSingleBed from "./public/images/coolcottage_single bed.jpg";

export const ROOM_GALLERY_IMAGES = [
  "https://i.postimg.cc/TwszpPZ5/mountview-bedroom.jpg",
  "https://i.postimg.cc/LXWcnsrY/mountview-bedrooms.jpg",
  "https://i.postimg.cc/76RFfLpb/mountview-bedroom-balcony.jpg",
  "https://i.postimg.cc/pTSwpdgp/mountview-campfire.jpg",
  "https://i.postimg.cc/76RFfLph/mountview-restoom.jpg",
];

export const VILLAS_DATA: Room[] = [
  {
    id: "mountain-view",
    name: "Mountain View Room (Left)",
    description: "Wake up to breathtaking panoramic views of the Nilgiri mountains. This cozy room features warm wooden interiors, queen bed, and a private balcony framing misty hilltops at sunrise.",
    ratePerNight: 3500,
    maxGuests: 4,
    sizeSquareMeter: 120,
    roomNumbers: ["101"],
    amenities: [
      "Panoramic Mountain View Balcony",
      "Queen Bed with Premium Linen",
      "Private Attached Bathroom",
      "Complimentary Morning Tea",
    ],
    highlights: [
      "Flat LCD Screen",
      "Wi-Fi Access",
      "24/7 Hot Water Access",
      "Shared Veranda Space",
      "Private Stairs Access to These Rooms",
      "Private Attached Bathroom",
      "Room Attendant",
      "UPS Battery Backup in Case of Power Cut",
    ],
    imageUrl: imgRoomsview,
    images: ROOM_GALLERY_IMAGES,
  },
  {
    id: "glass-house",
    name: "Glass House (Right)",
    description: "Wake up to breathtaking panoramic views of the Nilgiri mountains. This cozy room features warm wooden interiors, queen bed, and a private balcony framing misty hilltops at sunrise.",
    ratePerNight: 5500,
    maxGuests: 2,
    sizeSquareMeter: 150,
    roomNumbers: ["109"],
    amenities: [
      "270° Panoramic Glass Walls",
      "King Bed with Premium Linen",
      "Private Garden Deck",
      "Stargazing from Your Bed",
      "Private Attached Bathroom",
      "Morning Mist & Mountain Views",
    ],
    highlights: [
      "Flat LCD Screen",
      "Wi-Fi Access",
      "24/7 Hot Water Access",
      "Shared Veranda Space",
      "Private Stairs Access to These Rooms",
      "Private Attached Bathroom",
      "Room Attendant",
      "UPS Battery Backup in Case of Power Cut",
    ],
    imageUrl: "https://images.unsplash.com/photo-1508739773434-c26b3d09e071?auto=format&fit=crop&w=600&q=80",
    images: ROOM_GALLERY_IMAGES,
  },
  {
    id: "deluxe-family",
    name: "Deluxe Family Room",
    description: "Spacious family suite spread across two connected rooms (102 + 103) with an extra cot bed — ideal for families of up to 5. Features warm decor, ample storage, and a shared courtyard access.",
    ratePerNight: 4500,
    maxGuests: 5,
    sizeSquareMeter: 200,
    roomNumbers: ["102", "103"],
    isBundle: true,
    amenities: [
      "Two Connected Rooms (102 + 103)",
      "Family-Sized Reception",
      "Air Conditioning",
      "Private Bathrooms in Each Room",
      "Courtyard Garden Access",
    ],
    highlights: [
      "Flat LCD Screen",
      "Wi-Fi Access",
      "24/7 Hot Water Access",
      "Rooms Are Close to the Parking Area (No Steps/Stairs Involved)",
      "Private Attached Bathroom",
      "Room Attendant",
      "UPS Battery Backup in Case of Power Cut",
    ],
    imageUrl: imgBedrooms,
    images: ROOM_GALLERY_IMAGES,
  },
  {
    id: "extra-cot-room-104",
    name: "Extra Cot Bed Room (104)",
    description: "Comfortable room equipped with an extra fold-out cot bed, close to the parking area with no stairs involved. Perfect for small groups or families with a child.",
    ratePerNight: 3000,
    maxGuests: 3,
    sizeSquareMeter: 140,
    roomNumbers: ["104"],
    amenities: [
      "Double Bed + Extra Cot Bed",
      "Private Bathroom",
      "Wardrobe & Storage",
    ],
    highlights: [
      "Flat LCD Screen",
      "Wi-Fi Access",
      "24/7 Hot Water Access",
      "Rooms Are Close to the Parking Area (No Steps/Stairs Involved)",
      "Private Attached Bathroom",
      "Room Attendant",
      "UPS Battery Backup in Case of Power Cut",
    ],
    imageUrl: imgBedroom,
    images: ROOM_GALLERY_IMAGES,
  },
  {
    id: "extra-cot-room-105",
    name: "Extra Cot Bed Room (105) — Basement",
    description: "Comfortable basement-floor room equipped with an extra fold-out cot bed, offering a naturally cool temperature year-round. A budget-friendly option perfect for small groups or families with a child.",
    ratePerNight: 3000,
    maxGuests: 3,
    sizeSquareMeter: 140,
    roomNumbers: ["105"],
    amenities: [
      "Double Bed + Extra Cot Bed",
      "Private Bathroom",
      "Wardrobe & Storage",
      "Natural Cool Temperature",
    ],
    highlights: [
      "Flat LCD Screen",
      "Private Attached Bathroom",
      "Room Attendant",
      "UPS Battery Backup in Case of Power Cut",
      "Steps/Stairs Involved",
    ],
    imageUrl: imgBedroom,
    images: ROOM_GALLERY_IMAGES,
  },
  {
    id: "budget-basement",
    name: "Budget Double Room (Basement)",
    description: "Affordable and cozy double rooms on the basement floor, offering a cool natural temperature year-round. Includes optional extra cot bed. Great value for budget-conscious guests.",
    ratePerNight: 2500,
    maxGuests: 3,
    sizeSquareMeter: 100,
    roomNumbers: ["106", "107", "108"],
    amenities: [
      "Double Bed",
      "Natural Cool Temperature",
      "Private Bathroom",
      "Budget Friendly",
      "Wi-Fi Access",
    ],
    highlights: [
      "Flat LCD Screen",
      "Private Attached Bathroom",
      "Room Attendant",
      "UPS Battery Backup in Case of Power Cut",
      "Steps/Stairs Involved",
    ],
    imageUrl: imgSingleBed,
    images: ROOM_GALLERY_IMAGES,
  },
];

export const EXPERIENCES_DATA: Experience[] = [
  {
    id: "yacht-charter",
    name: "BESPOKE YACHT CRUISE",
    description: "Board our flagship 85ft luxury motor-yacht 'The Azure Pearl' for a half-day private island exploration. Includes bespoke champagne tastings, gourmet charcuterie, private skipper, and guided water-scooter reef snorkeling.",
    cost: 1800,
    duration: "4 Hours",
    category: "adventure",
    highlight: "Private Champagne Lounge",
    imageUrl: "https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?auto=format&fit=crop&q=80&w=600",
  },
  {
    id: "heli-picnic",
    name: "HELI-RIDGE PICNIC",
    description: "Take to the South Pacific skies in our high-altitude Airbus helicopter. Land upon a secluded volcanic ridge overlooking the entire archipelago to indulge in an ice-chilled wild caviar lunch paired with vintage champagne.",
    cost: 2400,
    duration: "2.5 Hours",
    category: "adventure",
    highlight: "Panoramic High-Altitude Views",
    imageUrl: "https://images.unsplash.com/photo-1540962351504-03099e0a754b?auto=format&fit=crop&q=80&w=600",
  },
  {
    id: "somatic-massage",
    name: "SANCTUARY SOMATIC MASSAGE",
    description: "Inhale oceanside serenity at our bamboo-vaulted spa garden. Three hours of custom hot volcanic rock therapies, deep-tissue somatic relaxation with local floral botanical elixirs, and thermal spring baths.",
    cost: 450,
    duration: "3 Hours",
    category: "wellness",
    highlight: "Warm Sea Salt Scrub",
    imageUrl: "https://images.unsplash.com/photo-1519699047748-de8e457a634e?auto=format&fit=crop&q=80&w=600",
  },
  {
    id: "shoreline-dining",
    name: "STARLIT DOME DINING",
    description: "Indulge in an exclusive private dining bubble inside a suspended glass sphere on the water's edge. Our Executive Chef crafts an 8-course local seafood & hand-reared Wagyu degustation paired with legendary wines.",
    cost: 600,
    duration: "Evening",
    category: "dining",
    highlight: "8-Course Degustation",
    imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&q=80&w=600",
  },
];

export const PACKAGES_DATA: SpecialPackage[] = [
  {
    id: "honeymoon-escape",
    name: "Romantic Getaway Package",
    tagline: "A tranquil couple's retreat in the Nilgiris",
    description: "5 nights in the Deluxe Family Room with stunning mountain surroundings, a private campfire evening, somatic spa session, and a starlit outdoor dining experience. Perfect for couples.",
    durationDays: 5,
    discountPercentage: 15,
    includedExperiences: ["somatic-massage", "shoreline-dining"],
    costMultiplier: 0.85,
  },
  {
    id: "ultimate-lumina-experience",
    name: "Mountain View Explorer Package",
    tagline: "Breathtaking views, adventure & luxury",
    description: "4 nights in the Mountain View Room with panoramic Nilgiri vistas, a helicopter ridge tour, private yacht charter, and an unforgettable hilltop dining experience.",
    durationDays: 4,
    discountPercentage: 10,
    includedExperiences: ["heli-picnic", "yacht-charter", "shoreline-dining"],
    costMultiplier: 0.9,
  },
];
